# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f60e4c7c52fa8d8fb406583e30df7789efec1bb5756accab489405277476c5bce927c91c51ea3995a48b3e62425d0224fe62523e21c3c9518a534042837a13
  w1_secret_key: 42345177725b75647463637b5272474f5469606b52625d6a62734b
  w1_merchant_id: 132444967456
  omniauth:
    vkontakte:
      key: "5624928"
      secret: "lfaZHss2pZSGkhdxxt53"
      scope: "offline,photos"
    odnoklassniki:
      key: "1248161280"
      public_key: "CBAPGGGLEBABABABA"
      secret: "F545EEDC75FDA95C4474F4C2"
      redirect_uri: "http://stager.dev:3000/users/auth/odnoklassniki/callback"
      scope: "VALUABLE_ACCESS,LONG_ACCESS_TOKEN"
      access_token: "tkn1wxNx15rdAH9QIPjLF7cUzDSRBCCCOrdD92bkv5zRdHNu3vtNenpeo0j4bvnzJ7bP0"
      secret_session_key: "7692e82ae3a8644f3bc219ca47201a6f"
    instagram:
      key: "4b3535f30d564b3b8d19b2510bce1cc0"
      secret: "125b7137b72341d6a5619ab01705cd67"


test:
  secret_key_base: 9a125658d8f1306d6eb1a206ae04cdd37c95647dca0ab57e2bfece7e07e2789c8a4e79100cf043e66fb01759b647bd2f40000d1d137a76e7006783674543b9a1

production:
  secret_key_base: 9a125658d8f1306d6eb1a206ae04cdd37c95647dca0ab57e2bfece7e07e2789c8a4e79100cf043e66fb01759b647bd2f40000d1d137a76e7006783674543b9a1
  w1_secret_key: 42345177725b75647463637b5272474f5469606b52625d6a62734b
  w1_merchant_id: 132444967456
  omniauth:
    vkontakte:
      key: "5642664"
      secret: "ZbSn0iS4XjjimUumu8ni"
      scope: "offline,photos"
    odnoklassniki:
      key: "1248300544"
      public_key: "CBAPIIGLEBABABABA"
      secret: "FCAF8CFD674CA5662E394168"
      redirect_uri: "http://myfundraise.ru/users/auth/odnoklassniki/callback"
      scope: "VALUABLE_ACCESS,LONG_ACCESS_TOKEN"
      access_token: "tkn14AedScWNhqCKDW4RxFMy5fuvbUl4BUiHvzJUDf6Fd8RhmNp30twuv4fwudjub7Lr92"
      secret_session_key: "d58e83e5086e71af4aa805a6f836c928"
    instagram:
      key: "4b3535f30d564b3b8d19b2510bce1cc0"
      secret: "125b7137b72341d6a5619ab01705cd67"
